title: Ryan Han
description: Personal website
baseurl: ""
url: "https://ryan99han.com"

markdown: kramdown
kramdown:
  math_engine: null
theme: null

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:slug/

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:slug/
